name: auto pull

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20-22 */7 * *' # Every minute, between 20:00 and 22:59, every 7 days

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git pull
      - name: Commit （注：如果这项失败了，可能是因为没有修改，不用太担心）
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "有更新！`date '+%Y-%m-%d %H:%M:%S'`）$GITHUB_RUN_ID

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
